
version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
    depends_on:
      - postgres
    networks:
      - internal
      - external
    ports:
      - "8000:8000"

  lobby:
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile.lobby
    depends_on:
      - postgres
    ports:
      - "8001:8001"

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
  
volumes:
  postgres-data: